## this relies on the match-docker-secret existing in AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: match-docker-secret-provider-class
  namespace: match
spec:
  provider: aws                             
  parameters: 
    objects: |
        - objectName: "match-docker-secret"
          objectType: "secretsmanager"
  secretObjects:
    - secretName: dockerconfig
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: "match-docker-secret"
          key: ".dockerconfigjson"