{{- if .Values.secretSyncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-syncer
  namespace: match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-syncer
  template:
    metadata:
      labels:
        app: secret-syncer
    spec:
      serviceAccountName: secret-sync-sa
      containers:
        - name: secret-syncer
          image: {{ .Values.secretSyncer.image }}
          command: ["sh", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - name: api-secrets
              mountPath: /mnt/api-secrets
              readOnly: true
            - name: docker-secrets
              mountPath: /mnt/docker-secrets
              readOnly: true
            - name: honeybadger-secrets
              mountPath: /mnt/honeybadger-secrets
              readOnly: true
            - name: user-secrets
              mountPath: /mnt/user-secrets
              readOnly: true
            - name: rds-secrets
              mountPath: /mnt/rds-secrets
              readOnly: true
            - name: redis-secrets
              mountPath: /mnt/redis-secrets
              readOnly: true
            {{- if .Values.smtp.enabled }}
            - name: smtp-secrets
              mountPath: /mnt/smtp-secrets
              readOnly: true
            {{- end }}
      volumes:
        - name: api-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-api-secret-provider-class
        - name: docker-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-docker-secret-provider-class
        - name: honeybadger-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-honeybadger-secret-provider-class
        - name: user-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-owning-user-credentials-secret-provider-class
        - name: rds-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-rds-secret-provider-class
        - name: redis-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-redis-secret-provider-class
        {{- if .Values.smtp.enabled }}
        - name: smtp-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: match-smtp-secret-provider-class
        {{- end }}
{{- end }}
