apiVersion: v2
name: secrets-configuration
description: A Helm chart to configure secrets for the Snicket Labs Match Reference Architecture. Depends on EKS ASCP and AWS Secrets Manager. 
type: application
version: 0.1.0