## this relies on the match-honeybadger-secret existing in AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: match-honeybadger-secret-provider-class
  namespace: match
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "match-honeybadger-secret"
        objectType: "secretsmanager"
        objectAlias: "honeybadger"
  secretObjects:
    - secretName: honeybadger-api
      type: Opaque
      data:
        - objectName: "honeybadger"
          key: "key"
