apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: match-rds-secret-provider-class
  namespace: match
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.rdsPgSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "db_name"
            objectAlias: "db_name"
          - path: "host"
            objectAlias: "host"
          - path: "password"
            objectAlias: "password"
          - path: "port"
            objectAlias: "port"
          - path: "username"
            objectAlias: "username"
  secretObjects:
    - secretName: "{{ .Values.clusterName }}-rds-pg"
      type: Opaque
      data:
        - key: db_name
          objectName: db_name
        - key: host
          objectName: host
        - key: password
          objectName: password
        - key: port
          objectName: port
        - key: username
          objectName: username